In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("survey_results_public.csv")
df.head()

ResponseId                                         MainBranch  \
0           1                     I am a developer by profession   
1           2             I am a student who is learning to code   
2           3  I am not primarily a developer, but I write co...   
3           4                     I am a developer by profession   
4           5                     I am a developer by profession   

                                          Employment  \
0  Independent contractor, freelancer, or self-em...   
1                                 Student, full-time   
2                                 Student, full-time   
3                                 Employed full-time   
4  Independent contractor, freelancer, or self-em...   

                                             Country US_State UK_Country  \
0                                           Slovakia      NaN        NaN   
1                                        Netherlands      NaN        NaN   
2                                 Russian Federation      NaN        NaN   
3                                            Austria      NaN        NaN   
4  United Kingdom of Great Britain and Northern I...      NaN    England   

                                             EdLevel     Age1stCode  \
0  Secondary school (e.g. American high school, G...  18 - 24 years   
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)  11 - 17 years   
2       Bachelor’s degree (B.A., B.S., B.Eng., etc.)  11 - 17 years   
3    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)  11 - 17 years   
4    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   5 - 10 years   

                                           LearnCode YearsCode  ...  \
0  Coding Bootcamp;Other online resources (ex: vi...       NaN  ...   
1  Other online resources (ex: videos, blogs, etc...         7  ...   
2  Other online resources (ex: videos, blogs, etc...       NaN  ...   
3                                                NaN       NaN  ...   
4                            Friend or family member        17  ...   

               Age Gender Trans                Sexuality  \
0  25-34 years old    Man    No  Straight / Heterosexual   
1  18-24 years old    Man    No  Straight / Heterosexual   
2  18-24 years old    Man    No        Prefer not to say   
3  35-44 years old    Man    No  Straight / Heterosexual   
4  25-34 years old    Man    No                      NaN   

                      Ethnicity                Accessibility  \
0  White or of European descent            None of the above   
1  White or of European descent            None of the above   
2             Prefer not to say            None of the above   
3  White or of European descent  I am deaf / hard of hearing   
4  White or of European descent            None of the above   

        MentalHealth           SurveyLength                  SurveyEase  \
0  None of the above  Appropriate in length                        Easy   
1  None of the above  Appropriate in length                        Easy   
2  None of the above  Appropriate in length                        Easy   
3                NaN  Appropriate in length  Neither easy nor difficult   
4                NaN  Appropriate in length                        Easy   

  ConvertedCompYearly  
0             62268.0  
1                 NaN  
2                 NaN  
3                 NaN  
4                 NaN  

[5 rows x 48 columns]

In [3]:
df = df[["Country", "YearsCodePro", "Employment", "ConvertedCompYearly"]]
df = df.rename({"ConvertedCompYearly": "Salary"}, axis=1)
df.head()

Country YearsCodePro  \
0                                           Slovakia          NaN   
1                                        Netherlands          NaN   
2                                 Russian Federation          NaN   
3                                            Austria          NaN   
4  United Kingdom of Great Britain and Northern I...           10   

                                          Employment   Salary  
0  Independent contractor, freelancer, or self-em...  62268.0  
1                                 Student, full-time      NaN  
2                                 Student, full-time      NaN  
3                                 Employed full-time      NaN  
4  Independent contractor, freelancer, or self-em...      NaN

In [4]:
df = df[df["Salary"].notnull()]
df.head()

Country YearsCodePro                                         Employment  \
0   Slovakia          NaN  Independent contractor, freelancer, or self-em...   
9     Sweden            4                                 Employed full-time   
11     Spain            5                                 Employed full-time   
12   Germany            6                                 Employed full-time   
16    Turkey            2                                 Employed full-time   

     Salary  
0   62268.0  
9   51552.0  
11  46482.0  
12  77290.0  
16  17748.0

In [5]:
df = df.dropna()
df

Country YearsCodePro  \
9                        Sweden            4   
11                        Spain            5   
12                      Germany            6   
16                       Turkey            2   
17                       Canada            6   
...                         ...          ...   
83434  United States of America            5   
83435                     Benin            2   
83436  United States of America            4   
83437                    Canada            3   
83438                    Brazil            4   

                                              Employment    Salary  
9                                     Employed full-time   51552.0  
11                                    Employed full-time   46482.0  
12                                    Employed full-time   77290.0  
16                                    Employed full-time   17748.0  
17                                    Employed full-time   46135.0  
...                                                  ...       ...  
83434                                 Employed full-time  160500.0  
83435  Independent contractor, freelancer, or self-em...    3960.0  
83436                                 Employed full-time   90000.0  
83437                                 Employed full-time  816816.0  
83438                                 Employed full-time   21168.0  

[46378 rows x 4 columns]

In [6]:
f = df[df["Employment"] == "Employed full-time"]
df = df.drop("Employment", axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46378 entries, 9 to 83438
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       46378 non-null  object 
 1   YearsCodePro  46378 non-null  object 
 2   Salary        46378 non-null  float64
dtypes: float64(1), object(2)
memory usage: 1.4+ MB


In [7]:
df['Country'].value_counts()

United States of America                                9803
India                                                   3750
Germany                                                 3222
United Kingdom of Great Britain and Northern Ireland    2918
Canada                                                  1721
                                                        ... 
Monaco                                                     1
Saint Vincent and the Grenadines                           1
Fiji                                                       1
Liberia                                                    1
Djibouti                                                   1
Name: Country, Length: 171, dtype: int64

In [8]:
def shorten_categories(categories, cutoff):
    categorical_map = {}
    for i in range(len(categories)):
        if categories.values[i] >= cutoff:
            categorical_map[categories.index[i]] = categories.index[i]
        else:
            categorical_map[categories.index[i]] = 'Other'
    return categorical_map

In [9]:


country_map = shorten_categories(df.Country.value_counts(), 400)
df['Country'] = df['Country'].map(country_map)
df.Country.value_counts()



United States of America                                9803
Other                                                   9532
India                                                   3750
Germany                                                 3222
United Kingdom of Great Britain and Northern Ireland    2918
Canada                                                  1721
France                                                  1622
Brazil                                                  1572
Poland                                                  1107
Netherlands                                             1052
Spain                                                   1027
Australia                                                948
Italy                                                    917
Russian Federation                                       871
Sweden                                                   820
Switzerland                                              561
Turkey                  

In [10]:
def clean_experience(x):
    if x ==  'More than 50 years':
        return 50
    if x == 'Less than 1 year':
        return 0.5
    return float(x)

df['YearsCodePro'] = df['YearsCodePro'].apply(clean_experience)

In [11]:
from sklearn.preprocessing import LabelEncoder
le_country = LabelEncoder()
df['Country'] = le_country.fit_transform(df['Country'])
df["Country"].unique()

array([21, 20,  9, 23,  5, 17,  8, 22, 25, 19, 12, 24, 26,  4, 13, 15, 18,
        2, 10,  7,  1,  3, 11,  0, 16,  6, 14])

In [12]:
X = df.drop("Salary", axis=1)
y = df["Salary"]
X

Country  YearsCodePro
9           21           4.0
11          20           5.0
12           9           6.0
16          23           2.0
17           5           6.0
...        ...           ...
83434       26           5.0
83435       17           2.0
83436       26           4.0
83437        5           3.0
83438        4           4.0

[46378 rows x 2 columns]

In [13]:
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()
linear_reg.fit(X, y.values)

LinearRegression()

In [14]:
y_pr = linear_reg.predict(X)
y_pr

array([129385.1591784 , 126903.06538916,  65679.2273211 , ...,
       158756.03131781,  32006.28769364,  29524.1939044 ])

In [15]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
error = np.sqrt(mean_squared_error(y, y_pr))
error

526193.1142948328

In [16]:
from sklearn.tree import DecisionTreeRegressor
dec_tree_reg = DecisionTreeRegressor(random_state=0)
dec_tree_reg.fit(X, y.values)

DecisionTreeRegressor(random_state=0)

In [17]:
y_pred = dec_tree_reg.predict(X)

error = np.sqrt(mean_squared_error(y, y_pred))
print("${:,.02f}".format(error))


$510,126.97


In [18]:
import pickle

In [19]:
data = {"model": dec_tree_reg, "le_country": le_country}
with open('saved_steps.pkl', 'wb') as file:
    pickle.dump(data, file)

In [20]:
with open('saved_steps.pkl', 'rb') as file:
    data = pickle.load(file)

regressor_loaded = data["model"]
le_country = data["le_country"]

In [21]:
y_pred = regressor_loaded.predict(X)
y_pred

array([ 65294.98412698,  78720.8125    ,  87225.17283951, ...,
       240766.57767722, 118322.80714286,  33329.48701299])